# Generated by Django 5.2.5 on 2025-08-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkExperience',
            new_name='MinorExperience',
        ),
    ]
