# Generated by Django 5.2.5 on 2025-08-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_rename_workexperience_minorexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='minorexperience',
            name='included',
            field=models.BooleanField(default=False),
        ),
    ]
